name: loginsignup
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  country_list_pick: ^1.0.1+6
  blurrycontainer: ^1.0.2
  country_pickers: ^2.0.0
  pinput: ^2.2.11
  connectivity_plus: ^2.3.5
  #  video_player: ^2.4.5
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Tiempos Headline
      fonts:
        - asset: assets/fonts/TiemposHeadline-Semibold.ttf
          style: normal

    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-SemiBold.ttf
          style: normal
        - asset: assets/fonts/Nunito-Bold.ttf
          style: normal

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
    - family: Andada Pro
      fonts:
        - asset: assets/fonts/AndadaPro-Bold.ttf
